# Generated by Django 2.1.4 on 2018-12-30 15:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0001_initial'),
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='team',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='team.Team'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='channelmember',
            name='role',
            field=models.IntegerField(choices=[(1, 'Admin'), (2, 'Member'), (3, 'Guest')], default=2),
        ),
    ]
