# Generated by Django 2.1.4 on 2018-12-30 17:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0001_initial'),
        ('chat', '0003_remove_channel_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='channelmember',
            name='user',
        ),
        migrations.AddField(
            model_name='channelmember',
            name='member',
            field=models.ForeignKey(default=-1, on_delete=django.db.models.deletion.PROTECT, to='team.TeamMember'),
            preserve_default=False,
        ),
    ]
