# Generated by Django 2.1.4 on 2018-12-30 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0007_remove_channelmember_role'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='message',
            table='messages',
        ),
    ]
