# Generated by Django 2.1.4 on 2019-01-18 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='is_public',
            field=models.BooleanField(default=False),
        ),
    ]
