# Generated by Django 2.1.4 on 2018-12-26 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discussions', '0002_auto_20181226_0652'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='wbs',
            field=models.CharField(max_length=60),
        ),
    ]
