# Generated by Django 2.1.4 on 2019-01-18 05:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('discussions', '0004_post_team'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='team',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='team.Team'),
        ),
    ]
